# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "hello all"
          command: "echo Hello, World!"
  build:
    docker:
      - image: cimg/base:stable  # Choose an appropriate Node.js version
    steps:
      - checkout
      - run:
          name: Update npm
          command: sudo apt-get update
      - run:
          name: Install npm
          command: sudo apt-get install npm
      - run:
          name: Create file path
          command: mkdir -p /home/circleci/project
      # - run:
      #     name: Change workdirectory
      #     command: cd /home/circleci/project
      # - run:
      #     name: Init npm
      #     command: npm init
      - run:
          name: Install Dependencies
          command: npm install --save-dev jest # or yarn install, depending on your setup
      - run:
          name: Build Website
          command: npm run build  # Replace with your build command
      - run:
          name: Test
          command: npx jest
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "ricardofecarva@gmail.com"
            git config --global user.name "ricardocarva"
            git clone --branch=gh-pages https://github.com/ricardocarva/repo.git gh-pages
            cp -R dist/* gh-pages/
            cd gh-pages
            git add .
            git commit -m "Deploy to GitHub Pages"
            git push origin gh-pages

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  build:
    jobs:
      - build