# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/base:stable  # Choose an appropriate Node.js version
    steps:
      - checkout
      - run:
          name: Update npm
          command: sudo apt-get update
      - run:
          name: Install npm
          command: sudo apt-get install npm
      - run:
          name: Install Dependencies
          command: npm install --save-dev jest
      - run:
          name: npx jest Test
          command: npx jest
  website_link_check:
    docker:
        # This image's Dockerfile is at runatlantis.io/Dockerfile
      - image: runatlantis/ci-link-checker:0.1
    steps:
      - checkout
      - run: yarn install
      - run: yarn website:build
      - run:
          name: http-server
          command: http-server runatlantis.io/.vuepress/dist
          background: true
        # We use dockerize -wait here to wait until the server is up.
      - run: |
          dockerize -wait tcp://localhost:8080 -- \
            muffet \
              -e 'https://github\.com/runatlantis/atlantis/edit/master/.*' \
              -e 'https://github.com/helm/charts/tree/master/stable/atlantis#customization' \
              http://localhost:8080/
    # check-links:
  #   docker:
  #     - image: node:14  # Choose an appropriate Node.js version
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install Dependencies
  #         command: npm install html-proofer
  #     - run:
  #         name: Verify html-proofer installation
  #         command: npm ls html-proofer
  #     - run:
  #         name: Verify html-proofer installation
  #         command: |
  #           /usr/local/bin/node -e "require('html-proofer')"
  #     - run:
  #         name: Check Links
  #         command: node src/link-checker.js

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  tests:
    jobs:
      - build
  link-checker:
    jobs:
      - website_link_check

      #       - run:
      #     name: Update npm
      #     command: sudo apt-get update
      # - run:
      #     name: Install npm
      #     command: sudo apt-get install npm
      # - run:
      #     name: Clear npm cache
      #     command: npm cache clean --force