# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/base:stable  # Choose an appropriate Node.js version
    steps:
      - checkout
      - run:
          name: Update npm
          command: sudo apt-get update
      - run:
          name: Install npm
          command: sudo apt-get install npm
      - run:
          name: Install Dependencies
          command: npm install --save-dev jest
      - run:
          name: npx jest Test
          command: npx jest

  link-check:
    docker:
      - image: cimg/base:stable  # Choose an appropriate Node.js version
    steps:
      - checkout
      - run:
          name: Update npm
          command: sudo apt-get update
      - run:
          name: Install npm
          command: sudo apt-get install npm
      - run:
          name: Install Link Checker
          command: npm install --save-dev link-checker
      - run:
          name: Check Links
          command: node check-links.js

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  tests:
    jobs:
      - build
  link-checker:
    jobs:
      - link-check

      #       - run:
      #     name: Update npm
      #     command: sudo apt-get update
      # - run:
      #     name: Install npm
      #     command: sudo apt-get install npm
      # - run:
      #     name: Clear npm cache
      #     command: npm cache clean --force